#server:
#  port: 8280
#  error:
#    whitelabel:
#      enabled: false
#      
#
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/book_management1
#    username: postgres
#    password: Raji@023
#
#    
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#       hibernate:
#        dialect: org.hibernate.dialect.PostgreSQL81Dialect
#  application:
#    name: customer-service
#
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defalutZone: http://localhost:8761/eureka

        